services:
  homepad-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homepad_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://customlab_user:customlab_password@host.docker.internal:5432/homepad_db}
      - APP_ENV=${APP_ENV:-local}
      - DEBUG=${DEBUG:-True}
    extra_hosts:
      - "host.docker.internal:host-gateway"
